# config.yml
# Application configuration file


paths:
  index_dir: "/data/indices"


services:
  document_processor_url: "http://services.aiopt.io:7000/v1/chn/chunking/"
  embedding_service_url: "http://services.aiopt.io:5000/v1/emd/embed-text/"
  ollama_base_url: "http://services.aiopt.io:11434"
  record_manager_db_url: "postgresql://postgres:mysecretpassword@localhost:5432/rag_db"

defaults:
  extractor_strategy: "docx"
  chunker_strategy: "token_based"
  retrieval_strategy: "hybrid_rrf"
  top_k: 5

llm:
  model_name: "gemma3:4b"


retriever_settings:
  adaptive:
    min_answer_length: 150
    retry_k: 7
  
prompt_templates:
  adaptive_retriever: |
    [INST]
    شما یک دستیار تحلیلی فارسی‌زبان و متخصص هستید. وظیفه شما این است که فقط بر اساس **متن ارائه‌شده**، به سؤالات به‌دقت و با دقت پاسخ دهید.

    برای تولید پاسخ، مراحل زیر را دنبال کنید:

    1.  **تحلیل پرسش کاربر:** هدف اصلی پرسش زیر را به‌درستی درک کنید: «{query}».
    2.  **بررسی دقیق متن:** تمام متن داده‌شده را با دقت بخوانید و جملات یا داده‌هایی را که مستقیماً به پرسش پاسخ می‌دهند، پیدا کنید.
    3.  **تدوین پاسخ:** یک پاسخ روشن، مختصر و مستقیم به زبان فارسی بنویسید که فقط بر اساس اطلاعات موجود در متن باشد.
    4.  **ارجاع به منبع (در صورت وجود):** اگر در متن اطلاعات منبع مثل شماره صفحه یا بخش آمده باشد، در پایان پاسخ به‌صورت کوتاه به آن اشاره کنید (مثلاً: «(صفحه ۱۲)»).
    5.  **در صورت نبود اطلاعات:** اگر پس از بررسی دقیق متن، پاسخی برای پرسش در آن پیدا نکردید، دقیقاً فقط این عبارت را بنویسید: «اطلاعاتی در متن ارائه نشده است.»

    **متن:**
    ---
    {context}
    ---

    **پرسش کاربر:** {query}
    [/INST]

    **پاسخ:**
